package Uni
// List of statuses such as "Playing game", "Listening song", etc
var statuses [][2]string = [][2]string{
// These being from the old UniBot code
[2]string{"Playing", "with discord on discord"},
[2]string{"Playing", "osu!"},
[2]string{"Playing", "Minecraft"},
[2]string{"Listening", "Metallica"},
[2]string{"Listening", "Theocracy"},
[2]string{"Playing", "Puella Magi Madoka Magica"},
[2]string{"Playing", "with other bots"},
[2]string{"Playing", "with a pony"},
[2]string{"Playing", "in a public server"},
[2]string{"Playing", "*boop*"},
[2]string{"Playing", "JoJo's Bizarre Adventure"},
[2]string{"Playing", "Death Note"},
[2]string{"Playing", "Parasyte"},
[2]string{"Playing", "with reddit's API"},
[2]string{"Playing", "with a VPN"},
[2]string{"Playing", "with https://github.com/ppy/osu"},
[2]string{"Playing", "with VirtualBox"},
[2]string{"Playing", "on derpibooru"},
[2]string{"Playing", "on windows 10"},
[2]string{"Playing", "Keep Talking And Nobody Explodes"},
[2]string{"Playing", "that game everyone plays"},
[2]string{"Playing", "My Hero Academia"},
[2]string{"Playing", "Attack On Titan"},
[2]string{"Listening", "Aurelleah"},
[2]string{"Listening", "Radiarc"},
[2]string{"Listening", "Jyc Row"},
[2]string{"Listening", "Reverb Brony"},
[2]string{"Listening", "Trivium"},
[2]string{"Playing", "on the nintendo switch"},
[2]string{"Playing", "in an emulator"},
[2]string{"Playing", "in VirtualBox"},
[2]string{"Playing", "with Virtual Machines"},
[2]string{"Playing", "Terraria"},
[2]string{"Playing", "Card Games"},
[2]string{"Playing", "Left 4 Dead 2"},
[2]string{"Playing", "Bejeweled Twist"},
[2]string{"Playing", "Starbound"},
[2]string{"Playing", "Oh...Sir! The Insult Simulator"},
[2]string{"Playing", "Papers, Please"},
[2]string{"Playing", "PAYDAY 2"},
[2]string{"Playing", "Portal 2"},
[2]string{"Playing", "Stick Fight: The Game"},
[2]string{"Listening", "Dragonforce - Defenders"},
[2]string{"Playing", "with SQLite3"},
[2]string{"Playing", "CrossCode"},
[2]string{"Playing", "with Python 4"},
[2]string{"Playing", "with golang 1.14"},
[2]string{"Listening", "Powerwolf - Blessed & Possessed"},
[2]string{"Listening", "Theocracy - I AM"},
[2]string{"Listening", "Metallica - One"},
[2]string{"Listening", "Metallica - ... And Justice For All"},
[2]string{"Listening", "Theocracy - Laying The Demon To Rest"},
[2]string{"Listening", "Theocracy - Wages Of Sin"},
[2]string{"Listening", "Theocracy - The Master Storyteller"},
[2]string{"Listening", "Iron Maiden - Ghost Of The Navigator"},
[2]string{"Listening", "Dark Moor - The Sphinx"},
[2]string{"Listening", "t+pazolite - Gifted Mutant"},
[2]string{"Listening", "Metallica - The Unforgiven III"},
[2]string{"Playing", "Terraria"},
[2]string{"Playing", "We Were Here"},
[2]string{"Playing", "UNO"},
[2]string{"Playing", "Starbound"},
[2]string{"Playing", "Team Fortress 2"},
[2]string{"Playing", "Rainbow Six Siege"},
[2]string{"Playing", "League of Legends"},
[2]string{"Playing", "The Sims 4"},
[2]string{"Playing", "Risk of Rain 2"},
[2]string{"Playing", "Garry's Mod"},
[2]string{"Playing", "A Certain Magical Index"},
[2]string{"Playing", "Diablo III"},
[2]string{"Playing", "Fallout 76"},
[2]string{"Playing", "ROBLOX"},
// Newer ones down here
[2]string{"Playing", "Apex Legends"},
[2]string{"Playing", "Town Of Salem"},
[2]string{"Playing", "MINDNIGHT"},
[2]string{"Playing", "Cataclysm: Dark Days Ahead"},
[2]string{"Listening", "Icewind Tales - To The Stars"},

}